# Generated by Django 5.1.2 on 2024-12-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_bookingdetails_loc_alter_bookingdetails_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketdetails', models.TextField()),
            ],
        ),
    ]
