# Generated by Django 5.1.2 on 2024-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_ticketdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='ticketdetails',
            field=models.JSONField(),
        ),
    ]
