# Generated by Django 5.1.2 on 2024-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_ticketdetails_ticketdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetails',
            name='ticketdetails',
            field=models.TextField(),
        ),
    ]
