# Generated by Django 5.1.2 on 2024-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField()),
                ('theatre_name', models.CharField(max_length=20)),
                ('movie_name', models.CharField(max_length=30)),
                ('audio', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=2)),
                ('seat_number', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
